main: cn.wode490390.nukkit.biomefixer.BiomeFixer
name: "BiomeFixer"
description: "Biome fixer plugin for Nukkit"
author: "wode490390"
website: "http://wode490390.cn/"
version: "${pom.version}"
api: ["1.0.0"]
load: POSTWORLD
permissions:
  biomefixer.command:
    description: "Allows player to use all commands of BiomeFixer plugin"
    default: op
